export const SOCKET_EVENTS = {
  ROOM_CREATE: "room:create",
  ROOM_JOIN: "room:join",
  ROOM_LOCK: "room:lock",
  ROOM_UNLOCK: "room:unlock",
  ROOM_LEAVE: "room:leave",
  SIGNAL: "signal",
  CHAT_SEND: "chat:send",
  REACTION_SEND: "reaction:send",
  CONTROL_GRANT: "control:grant",
  CONTROL_REVOKE: "control:revoke",
  CONTROL_REQUEST: "control:request",
  CONTROL_APPROVE: "control:approve",
  ROOM_CREATED: "room:created",
  ROOM_JOINED: "room:joined",
  ROOM_ENDED: "room:ended",
  ROOM_LOCKED: "room:locked",
  ROOM_UNLOCKED: "room:unlocked",
  MEMBER_JOINED: "member:joined",
  MEMBER_LEFT: "member:left",
  MEMBER_CONTROL_CHANGED: "member:control:changed",
  CONTROL_REQUESTED: "control:requested",
  CHAT_MESSAGE: "chat:message",
  REACTION: "reaction",
  SOCKET_ID_META: "socket-id-meta",
  APP_ERROR: "app:error",
} as const;
